export const dummyInvoice = {
  invoiceTitle: "Invoice",
  businessAddress: "XYZ Street, USA",
  businessEmail: "info@samplecompany.com",
  businessPhone: "9876543210",
  businessLogo: "./chanel-1.jpg",
  clientId: "",
  clientName: "Abhishek Kumar",
  clientEmail: "info@xyz.com",
  clientPhone: "+91-1234567890",
  clientAddress: "New Delhi, India",
  clientTaxId: "GSTIN-11223344",
  invoiceTitle: "Invoice",
  invoiceNumber: "INV-123",
  dueDate: "2025-05-24",
  paymentTerms: "Net 30",
  subtotal: 300,
  tax: 40.5,
  discount: 120,
  totalAmount: 328.6,
  notes: "Thank you for your business!",
  paymentInstructions: "Please make payment to the bank account provided.",
  items: [
    {
      description: "Toothbrush",
      quantity: 15,
      rate: 10,
      discount: 0,
      total: 1150,
    },
    {
      description: "Toothpaste",
      quantity: 10,
      rate: 15,
      discount: 0,
      total: 130,
    },
  ],
  deductions: [
    {
      description: "Discounts:",
      amount: 30,
      percent: 10,
    },
  ],
  additions: [
    {
      description: "IGST @ 18%:",
      amount: 4118.6,
      percent: 9,
    },
  ],
  issuedAt: "2025-04-24",
};
